# Generated by Django 5.2.14 on 2026-08-28 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('analyst_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('experience_years', models.IntegerField(default=3)),
                ('current_workload', models.IntegerField(default=0)),
                ('maximum_capacity', models.IntegerField(default=10)),
                ('active_tickets', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['analyst_id'],
            },
        ),
        migrations.CreateModel(
            name='QueueRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_tickets', models.IntegerField(default=0)),
                ('high_risk_before', models.IntegerField(default=0)),
                ('high_risk_after', models.IntegerField(default=0)),
                ('expected_breaches_before', models.FloatField(default=0.0)),
                ('expected_breaches_after', models.FloatField(default=0.0)),
                ('breaches_avoided', models.FloatField(default=0.0)),
                ('breach_reduction_pct', models.FloatField(default=0.0)),
                ('average_queue_delay_before', models.FloatField(default=0.0)),
                ('average_queue_delay_after', models.FloatField(default=0.0)),
                ('delay_reduction_pct', models.FloatField(default=0.0)),
                ('number_of_reassignments', models.IntegerField(default=0)),
                ('number_of_escalations', models.IntegerField(default=0)),
                ('number_of_prioritizations', models.IntegerField(default=0)),
                ('number_kept_current', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SLARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20, unique=True)),
                ('sla_hours', models.FloatField(default=4.0)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['severity'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('incident_type', models.CharField(default='Malware', max_length=64)),
                ('source', models.CharField(default='SIEM', max_length=64)),
                ('attack_vector', models.CharField(default='Endpoint', max_length=64)),
                ('priority', models.CharField(default='P3', max_length=16)),
                ('affected_systems', models.IntegerField(default=5)),
                ('users_affected', models.IntegerField(default=15)),
                ('threat_score', models.FloatField(default=50.0)),
                ('analyst_experience_years', models.IntegerField(default=3)),
                ('current_queue', models.IntegerField(default=10)),
                ('available_analysts', models.IntegerField(default=5)),
                ('sla_hours', models.FloatField(default=4.0)),
                ('historical_incidents', models.IntegerField(default=20)),
                ('time_of_day', models.CharField(default='Morning', max_length=32)),
                ('day_of_week', models.CharField(default='Mon', max_length=16)),
                ('assigned_analyst', models.CharField(default='A01', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('predicted_severity', models.CharField(blank=True, default='', max_length=32)),
                ('predicted_resolution_hours', models.FloatField(blank=True, null=True)),
                ('predicted_queue_delay', models.FloatField(blank=True, null=True)),
                ('predicted_workload', models.FloatField(blank=True, null=True)),
                ('sla_breach_probability_before', models.FloatField(blank=True, null=True)),
                ('sla_breach_probability_after', models.FloatField(blank=True, null=True)),
                ('recommended_action', models.CharField(blank=True, default='KEEP_CURRENT', max_length=32)),
                ('assigned_analyst_after', models.CharField(blank=True, default='', max_length=32)),
                ('escalation_priority', models.CharField(blank=True, default='P3', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('original_position', models.IntegerField(blank=True, null=True)),
                ('new_position', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['new_position', 'original_position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=64)),
                ('old_position', models.IntegerField(default=1)),
                ('new_position', models.IntegerField(default=1)),
                ('old_analyst', models.CharField(max_length=32)),
                ('new_analyst', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('sla_risk_before', models.FloatField(default=0.0)),
                ('sla_risk_after', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('queue_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.queuerun')),
            ],
            options={
                'ordering': ['new_position'],
            },
        ),
    ]
