import React from 'react';
import { HelpCircle, RefreshCw, AlertTriangle, ArrowUp, CheckCircle, X } from 'lucide-react';

export function DecisionLogModal({ decisions, isOpen, onClose }) {
  if (!isOpen) return null;

  const getActionIcon = (action) => {
    switch (action) {
      case 'REASSIGN': return <RefreshCw size={14} color="#38bdf8" />;
      case 'ESCALATE': return <AlertTriangle size={14} color="#f43f5e" />;
      case 'PRIORITIZE': return <ArrowUp size={14} color="#fbbf24" />;
      default: return <CheckCircle size={14} color="#94a3b8" />;
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '18px' }}>
          <h3 style={{ fontSize: '1.2rem', fontWeight: 800, display: 'flex', alignItems: 'center', gap: '8px' }}>
            <HelpCircle size={20} color="var(--cyan-primary)" />
            AI Decision Rationale Audit Log
          </h3>
          <button className="btn btn-secondary" style={{ padding: '6px' }} onClick={onClose}>
            <X size={18} />
          </button>
        </div>

        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '18px' }}>
          Deterministic mathematical justifications generated by the Queue Optimizer for every re-planning action.
        </p>

        <div className="table-container" style={{ maxHeight: '480px' }}>
          <table className="soc-table">
            <thead>
              <tr>
                <th>Ticket ID</th>
                <th>Position Shift</th>
                <th>Analyst Transition</th>
                <th>Action</th>
                <th>SLA Risk Shift</th>
                <th>Deterministic Explanation</th>
              </tr>
            </thead>
            <tbody>
              {!decisions || decisions.length === 0 ? (
                <tr>
                  <td colSpan={6} style={{ textAlign: 'center', padding: '30px', color: 'var(--text-muted)' }}>
                    No optimization decisions logged yet. Run AI Optimization to generate decisions.
                  </td>
                </tr>
              ) : (
                decisions.map((d, idx) => (
                  <tr key={idx}>
                    <td style={{ fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
                      <span style={{ color: 'var(--cyan-primary)' }}>{d.ticket_id}</span>
                    </td>
                    <td className="font-mono" style={{ fontSize: '0.8rem' }}>
                      #{d.old_position} &rarr; #{d.new_position}
                    </td>
                    <td style={{ fontFamily: 'var(--font-mono)' }}>
                      {d.old_analyst !== d.new_analyst ? (
                        <span>
                          <span style={{ color: 'var(--text-muted)' }}>{d.old_analyst}</span>
                          <span style={{ margin: '0 4px', color: 'var(--cyan-primary)' }}>&rarr;</span>
                          <strong style={{ color: '#38bdf8' }}>{d.new_analyst}</strong>
                        </span>
                      ) : (
                        <span>{d.new_analyst}</span>
                      )}
                    </td>
                    <td>
                      <span className="badge" style={{ gap: '4px' }}>
                        {getActionIcon(d.action)}
                        {d.action}
                      </span>
                    </td>
                    <td className="font-mono">
                      <span style={{ color: 'var(--text-muted)' }}>{d.sla_risk_before}%</span>
                      <span style={{ margin: '0 4px', color: 'var(--cyan-primary)' }}>&rarr;</span>
                      <strong style={{ color: d.sla_risk_after < 30 ? '#34d399' : '#fbbf24' }}>{d.sla_risk_after}%</strong>
                    </td>
                    <td style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', lineHeight: '1.4' }}>
                      {d.reason}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '18px' }}>
          <button className="btn btn-secondary" onClick={onClose}>Close Audit Log</button>
        </div>
      </div>
    </div>
  );
}
